export const DATES = [
  {
    id: "impro",
    num: "01",
    tag: "Valeur sûre",
    tagClass: "",
    title: "Le Spectacle d'Impro",
    desc: "Café-théâtre, impro à 100 à l'heure et fous rires garantis. Je l'ai déjà vue : elle est vraiment très forte, tu vas adorer.",
    meta: [
      { icon: "📅", text: "Jeudi soir" },
      { icon: "📍", text: "Au Petit Chapeau Rond Rouge — Etterbeek" },
    ],
    link: { label: "Voir l'événement", url: "https://shop.utick.net/?module=ACTIVITYSERIEDETAILS&pos=LEPETITCHAPEAURONDROUGE&s=49B54AE4-1FE7-44E4-5EB8-EEB45266B61B" },
    copyLine: "Le spectacle d'impro jeudi au Petit Chapeau Rond Rouge",
  },
  {
    id: "hache",
    num: "02",
    tag: "Pour monter d'un cran",
    tagClass: "hot",
    title: "Le Lancer de Hache",
    desc: "Le staff t'apprend, c'est carrément sécurisé, et planter une hache dans une cible c'est étrangement satisfaisant. Effet « wow » garanti et beaucoup de fous rires.",
    meta: [
      { icon: "📍", text: "WoodCutter — près des Marolles" },
      { rating: true, stars: "★★★★★", text: "4,8 · ~2000 avis" },
    ],
    link: null,
    copyLine: "Le lancer de hache au WoodCutter (mode warrior 🪓)",
  },
  {
    id: "frites",
    num: "03",
    tag: "Complet",
    tagClass: "full",
    locked: true,
    stamp: "Complet",
    stampClass: "",
    lockText: "Victime de son succès",
    title: "Les Frites Des Voisins",
    desc: "Dégustation d'un assortiment de frites molles de la table des voisins. Malheureusement victime de son succès — complet jusqu'à nouvel ordre. On se console comme on peut.",
    meta: [
      { icon: "📍", text: "La table des voisins" },
    ],
    link: null,
    copyLine: null,
  },
  {
    id: "jiujitsu",
    num: "04",
    tag: "Sport",
    tagClass: "joke",
    locked: true,
    stamp: "Indisponible",
    stampClass: "joke",
    lockText: "Coach déjà pris 🥋",
    title: "Le Cours de Jiu-Jitsu",
    desc: "Un entraînement privé où le coach Martin t'apprend ses meilleures techniques. Tenue fournie, ego pas garanti. Les places partent vite.",
    meta: [
      { icon: "🥋", text: "Coaching (très) privé par Martin" },
    ],
    link: null,
    copyLine: null,
  },
  {
    id: "lln",
    num: "05",
    tag: "Évasion",
    tagClass: "",
    title: "Louvain-la-Neuve",
    desc: "Une immersion dans la magnifique ville de Louvain-la-Neuve : resto et bar au programme. Parce que, soyons honnêtes, il n'y a pas grand-chose d'autre à faire à Louvain-la-Neuve.",
    meta: [
      { icon: "🚆", text: "Resto + bar" },
    ],
    link: null,
    copyLine: "Une escapade à Louvain-la-Neuve (resto + bar)",
  },
  {
    id: "cambre",
    num: "06",
    tag: "Si le soleil est de la partie",
    tagClass: "",
    title: "Apéro au Bois de la Cambre",
    desc: "S'il fait beau, on se pose au Bois de la Cambre avec un bon apéro. Canards et foulques en figuration, ambiance détente garantie.",
    meta: [
      { icon: "🦆", text: "Apéro + nature" },
    ],
    link: null,
    copyLine: "Un apéro au Bois de la Cambre (avec les foulques 🦆)",
  },
];
